import { MigrationInterface, QueryRunner } from 'typeorm'

export class AddUsersTable1736552326213 implements MigrationInterface {
    name = 'AddUsersTable1736552326213'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "chat_flow" DROP CONSTRAINT "FK_1490f1a525c5a99d315c6db89bc"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_f56c36fe42894d57e5c664d229"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_e76bae1780b77e56aab1h2asd4"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_e213b811b01405a42309a6a410"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_f56c36fe42894d57e5c664d230"`)
        await queryRunner.query(`ALTER TABLE "chat_flow" DROP COLUMN "owner_id"`)
        await queryRunner.query(`ALTER TABLE "chat_message" ALTER COLUMN "chatType" DROP DEFAULT`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "name"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "name" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "email"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "email" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "phone"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "phone" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "variable" ALTER COLUMN "value" DROP NOT NULL`)
        await queryRunner.query(`ALTER TABLE "variable" ALTER COLUMN "type" SET NOT NULL`)
        await queryRunner.query(`ALTER TABLE "variable" ALTER COLUMN "type" SET DEFAULT 'string'`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "name"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "name" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "description"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "description" text`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "status"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "status" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store_file_chunk" ALTER COLUMN "pageContent" SET NOT NULL`)
        await queryRunner.query(`ALTER TABLE "chat_message_feedback" ALTER COLUMN "rating" DROP NOT NULL`)
        await queryRunner.query(`ALTER TABLE "upsert_history" DROP COLUMN "result"`)
        await queryRunner.query(`ALTER TABLE "upsert_history" ADD "result" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "upsert_history" DROP COLUMN "flowData"`)
        await queryRunner.query(`ALTER TABLE "upsert_history" ADD "flowData" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP CONSTRAINT "PK_96109043dd704f53-9830ab78f0"`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "id"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "id" character varying(20) NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD CONSTRAINT "PK_0a1358bea3e5a3ba047b6e4959c" PRIMARY KEY ("id")`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "apiKey"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "apiKey" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "apiSecret"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "apiSecret" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "keyName"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "keyName" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "description"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "description" text`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "badge"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "badge" text`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "framework"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "framework" text`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "usecases"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "usecases" text`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "type"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "type" text`)
        await queryRunner.query(`CREATE INDEX "IDX_e28550b1dd9e091193fa3ed22a" ON "document_store_file_chunk" ("docId") `)
        await queryRunner.query(`CREATE INDEX "IDX_c791442eeab0fbf5219b6f78c0" ON "document_store_file_chunk" ("storeId") `)
        await queryRunner.query(`CREATE INDEX "IDX_f56c36fe42894d57e5c664d229" ON "chat_message_feedback" ("chatflowid") `)
        await queryRunner.query(`CREATE INDEX "IDX_4572bbe0437c04b9842d802a0c" ON "upsert_history" ("chatflowid") `)
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_4572bbe0437c04b9842d802a0c"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_f56c36fe42894d57e5c664d229"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_c791442eeab0fbf5219b6f78c0"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_e28550b1dd9e091193fa3ed22a"`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "type"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "type" character varying`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "usecases"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "usecases" character varying`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "framework"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "framework" character varying`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "badge"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "badge" character varying`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "description"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "description" character varying`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "keyName"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "keyName" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "apiSecret"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "apiSecret" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "apiKey"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "apiKey" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP CONSTRAINT "PK_0a1358bea3e5a3ba047b6e4959c"`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "id"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD CONSTRAINT "PK_96109043dd704f53-9830ab78f0" PRIMARY KEY ("id")`)
        await queryRunner.query(`ALTER TABLE "upsert_history" DROP COLUMN "flowData"`)
        await queryRunner.query(`ALTER TABLE "upsert_history" ADD "flowData" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "upsert_history" DROP COLUMN "result"`)
        await queryRunner.query(`ALTER TABLE "upsert_history" ADD "result" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "chat_message_feedback" ALTER COLUMN "rating" SET NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store_file_chunk" ALTER COLUMN "pageContent" DROP NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "status"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "status" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "description"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "description" character varying`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "name"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "name" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "variable" ALTER COLUMN "type" DROP DEFAULT`)
        await queryRunner.query(`ALTER TABLE "variable" ALTER COLUMN "type" DROP NOT NULL`)
        await queryRunner.query(`ALTER TABLE "variable" ALTER COLUMN "value" SET NOT NULL`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "phone"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "phone" text`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "email"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "email" text`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "name"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "name" text`)
        await queryRunner.query(`ALTER TABLE "chat_message" ALTER COLUMN "chatType" SET DEFAULT 'INTERNAL'`)
        await queryRunner.query(`ALTER TABLE "chat_flow" ADD "owner_id" uuid`)
        await queryRunner.query(`CREATE INDEX "IDX_f56c36fe42894d57e5c664d230" ON "chat_message_feedback" ("chatflowid") `)
        await queryRunner.query(`CREATE INDEX "IDX_e213b811b01405a42309a6a410" ON "document_store_file_chunk" ("storeId") `)
        await queryRunner.query(`CREATE INDEX "IDX_e76bae1780b77e56aab1h2asd4" ON "document_store_file_chunk" ("docId") `)
        await queryRunner.query(`CREATE INDEX "IDX_f56c36fe42894d57e5c664d229" ON "chat_message" ("chatflowid") `)
        await queryRunner.query(
            `ALTER TABLE "chat_flow" ADD CONSTRAINT "FK_1490f1a525c5a99d315c6db89bc" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`
        )
    }
}
